# Hachimi App — Static Analysis Configuration
#
# Base: flutter_lints (recommended Flutter rules)
# Extended with project-specific stricter rules for code quality.

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Code style
    prefer_single_quotes: true
    always_declare_return_types: true
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    sort_child_properties_last: true
    use_full_hex_values_for_flutter_colors: true

    # Safety
    avoid_dynamic_calls: true
    cancel_subscriptions: true
    close_sinks: true

    # Readability
    unnecessary_lambdas: true
    prefer_is_empty: true
    avoid_unnecessary_containers: true

analyzer:
  errors:
    avoid_print: error
