/// 成就名称与描述的扩展语言包（ja / ko / zh-Hant）。
/// 与 [AchievementStrings] 配合使用，由主类的 name/desc/titleName 方法引用。
class AchievementStringsExt {
  AchievementStringsExt._();

  // ─── 日本語名称 ───

  static const Map<String, String> namesJa = {
    'quest_first_session': '最初の足跡',
    'quest_100_sessions': 'センチュリークラブ',
    'quest_3_habits': 'トリプルスレット',
    'quest_5_habits': 'フルハウス',
    'quest_all_done': '完全制覇',
    'quest_5_workdays': '平日の戦士',
    'quest_first_checkin': 'おはよう猫',
    'quest_marathon': 'マラソンキャット',
    'hours_100': '百時間の旅',
    'hours_1000': '千時間マスター',
    'goal_on_time': '時間通り',
    'goal_ahead': '先手必勝',
    'cat_first_adopt': 'おかえりなさい',
    'cat_3_adopted': '猫コレクター',
    'cat_adolescent': '成長期',
    'cat_adult': '一人前',
    'cat_senior': '達人猫',
    'cat_graduated': '卒業の日',
    'cat_accessory': 'おしゃれ猫',
    'cat_5_accessories': 'ワードローブの女王',
    'cat_all_happy': '幸せ家族',
    'persist_1': 'ラッキーデイ',
    'persist_2': '唯一の道',
    'persist_3': '三位一体',
    'persist_4': '四大元素',
    'persist_5': '氷を破る',
    'persist_6': 'ヘキサグラム',
    'persist_7': '創世記',
    'persist_8': '格闘メダル',
    'persist_9': '月面着陸',
    'persist_10': 'ボッカチオの祝福',
    'persist_11': 'アポロ17号',
    'persist_12': '十二章',
    'persist_13': '冷戦メダル',
    'persist_14': 'ソネット詩人',
    'persist_15': '満月メダル',
    'persist_16': 'オリンピックの旅',
    'persist_17': '独立宣言',
    'persist_18': '風の歌を聴け',
    'persist_19': '雅の書',
    'persist_20': '運命のダイス',
    'persist_21': 'マハトマ勲章',
    'persist_22': 'ブリザードメダル',
    'persist_23': 'テンプル騎士団',
    'persist_24': 'ノルマンディー勲章',
    'persist_25': '円卓の騎士',
    'persist_26': '鉄のメダル',
    'persist_27': '進化の手',
    'persist_28': '二十八宿',
    'persist_29': '閏日',
    'persist_30': '月の裏側',
    'persist_31': '独裁官',
    'persist_32': '白黒決戦',
    'persist_33': '予言の子',
    'persist_35': '三界の師',
    'persist_36': '不屈の猪',
    'persist_38': 'シェイクスピア勲章',
    'persist_41': 'モーツァルトの楽章',
    'persist_42': 'マラソンメダル',
    'persist_44': 'ブリタニアへ',
    'persist_45': 'ハーフタイムメダル',
    'persist_47': 'AK-47',
    'persist_48': '秋葉原アイドル',
    'persist_50': '孟子の教え',
    'persist_51': 'エリア51訪問者',
    'persist_52': 'パラレルワールド',
    'persist_53': 'プレーオフの伝説',
    'persist_54': 'ジョーカーカード',
    'persist_59': 'フライヤー1号',
    'persist_60': '孔子の耳順',
    'persist_64': '任天堂スピリット',
    'persist_69': 'フリークエントフライヤー',
    'persist_71': '青い惑星',
    'persist_72': '斉天大聖',
    'persist_73': '富嶽三十六景',
    'persist_76': '彗星の旅',
    'persist_77': '七夕の星',
    'persist_78': 'タロットの運',
    'persist_79': '惑星周回',
    'persist_80': 'ヴェルヌのチケット',
    'persist_81': '鬼滅の刃',
    'persist_84': '残酷な天使',
    'persist_85': '不屈の精神',
    'persist_86': '象のメダル',
    'persist_88': '水星の旅',
    'persist_90': '四半期の伝説',
    'persist_91': 'ケツァルコアトルの塔',
    'persist_92': '核燃料',
    'persist_95': '至高の位',
    'persist_99': 'あと一歩',
    'persist_100': '百折不撓',
    'persist_101': '台北一望',
    'persist_108': '英雄集結',
    'persist_112': '脱出速度',
    'persist_116': '百年戦争',
    'persist_120': 'フィルム時代',
    'persist_122': '最長の人生',
    'persist_125': 'パンテオン',
    'persist_128': 'マッキントッシュ勲章',
    'persist_135': 'フィルムバッジ',
    'persist_137': '地球C-137',
    'persist_144': '麻雀の起源',
    'persist_146': 'ピラミッドの奇跡',
    'persist_150': 'ノアの方舟',
    'persist_151': 'ポケットモンスター',
    'persist_155': 'ビリヤードの伝説',
    'persist_165': '凍てつく青星',
    'persist_167': '太陽系の彼方',
    'persist_168': '吉祥如意',
    'persist_175': '第一適格者',
    'persist_180': '三角形メダル',
    'persist_193': '国連バッジ',
    'persist_197': '黄金バッジ',
    'persist_206': 'チェルノブイリ勲章',
    'persist_214': '康煕字典',
    'persist_225': '金星',
    'persist_240': 'モスクワの星',
    'persist_243': '金星植民地',
    'persist_249': '万物生成',
    'persist_250': '銀河系メダル',
    'persist_255': '亀の祝福',
    'persist_260': 'マヤの時代',
    'persist_277': 'モスクワの海',
    'persist_280': '新しい命',
    'persist_282': 'ハンムラビ法典',
    'persist_287': '地底探検',
    'persist_293': '古代オリンピック',
    'persist_294': '資治通鑑',
    'persist_305': '風雅頌',
    'persist_314': 'アルキメデス',
    'persist_322': '突破口',
    'persist_324': 'エッフェル塔',
    'persist_333': '東京タワー',
    'persist_360': 'メソポタミアの数学',
    'persist_361': '碁盤',
    'persist_365': '四季',
    'persist_366': '閏年の約束',
    'persist_382': '断食チャンピオン',
    'persist_400': 'トラックメダル',
    'persist_403': 'HTTP 403',
    'persist_404': '遺失物取扱所',
    'persist_410': 'エンパイアステート',
    'persist_419': 'コスモス419',
    'persist_437': '宇宙飛行士',
    'persist_500': '五行山',
    'persist_507': '明の真珠',
    'persist_512': 'ナイチンゲール勲章',
    'persist_520': '愛の告白',
    'persist_525': '宇宙の放浪者',
    'persist_527': 'コロッセオ',
    'persist_601': '巡礼の鐘',
    'persist_666': 'ピンクユニコーン',
    'persist_687': '火星基地',
    'persist_828': 'ドバイの頂点',
    'persist_878': '宇宙遊泳者',
    'persist_930': '最初の一人',
    'persist_1420': '祈年殿',
    'persist_2997': '光速メダル',
  };

  // ─── 한국어 이름 ───

  static const Map<String, String> namesKo = {
    'quest_first_session': '첫 번째 발자국',
    'quest_100_sessions': '센추리 클럽',
    'quest_3_habits': '트리플 스레트',
    'quest_5_habits': '풀 하우스',
    'quest_all_done': '완벽한 하루',
    'quest_5_workdays': '평일의 전사',
    'quest_first_checkin': '아침 고양이',
    'quest_marathon': '마라톤 캣',
    'hours_100': '백시간 여정',
    'hours_1000': '천시간 마스터',
    'goal_on_time': '제시간에',
    'goal_ahead': '앞서가기',
    'cat_first_adopt': '어서 와',
    'cat_3_adopted': '고양이 수집가',
    'cat_adolescent': '성장 중',
    'cat_adult': '다 큰 고양이',
    'cat_senior': '달인 고양이',
    'cat_graduated': '졸업의 날',
    'cat_accessory': '패션 고양이',
    'cat_5_accessories': '옷장의 여왕',
    'cat_all_happy': '행복한 가족',
    'persist_1': '행운의 날',
    'persist_2': '유일한 길',
    'persist_3': '삼위일체',
    'persist_4': '사대 원소',
    'persist_5': '얼음을 깨다',
    'persist_6': '헥사그램',
    'persist_7': '창세기',
    'persist_8': '격투 메달',
    'persist_9': '달 착륙',
    'persist_10': '보카치오의 축복',
    'persist_11': '아폴로 17호',
    'persist_12': '열두 장',
    'persist_13': '냉전 메달',
    'persist_14': '소네트 시인',
    'persist_15': '보름달 메달',
    'persist_16': '올림픽 여정',
    'persist_17': '독립 선언',
    'persist_18': '바람의 노래를 들어라',
    'persist_19': '아름다운 책',
    'persist_20': '운명의 주사위',
    'persist_21': '마하트마 훈장',
    'persist_22': '블리자드 메달',
    'persist_23': '성전 기사 훈장',
    'persist_24': '노르망디 훈장',
    'persist_25': '원탁의 기사',
    'persist_26': '강철 메달',
    'persist_27': '진화의 손',
    'persist_28': '이십팔수',
    'persist_29': '윤일',
    'persist_30': '달의 뒷면',
    'persist_31': '독재관',
    'persist_32': '흑백 대결',
    'persist_33': '예언의 아이',
    'persist_35': '삼계의 스승',
    'persist_36': '불굴의 돼지',
    'persist_38': '셰익스피어 훈장',
    'persist_41': '모차르트의 악장',
    'persist_42': '마라톤 메달',
    'persist_44': '브리타니아로',
    'persist_45': '하프타임 메달',
    'persist_47': 'AK-47',
    'persist_48': '아키하바라 아이돌',
    'persist_50': '맹자의 가르침',
    'persist_51': '에리어 51 방문자',
    'persist_52': '평행 우주',
    'persist_53': '플레이오프 전설',
    'persist_54': '조커 카드',
    'persist_59': '플라이어 1호',
    'persist_60': '공자의 이순',
    'persist_64': '닌텐도 스피릿',
    'persist_69': '에어 마일리지',
    'persist_71': '푸른 행성',
    'persist_72': '제천대성',
    'persist_73': '후지산 36경',
    'persist_76': '혜성의 여정',
    'persist_77': '견우직녀',
    'persist_78': '타로 운세',
    'persist_79': '행성 궤도',
    'persist_80': '베른의 티켓',
    'persist_81': '퇴마사',
    'persist_84': '잔혹한 천사',
    'persist_85': '불굴의 의지',
    'persist_86': '코끼리 메달',
    'persist_88': '수성의 여정',
    'persist_90': '분기의 전설',
    'persist_91': '케찰코아틀 피라미드',
    'persist_92': '핵연료',
    'persist_95': '지존의 자리',
    'persist_99': '한 걸음 앞',
    'persist_100': '백절불굴',
    'persist_101': '타이베이 전망',
    'persist_108': '영웅 집결',
    'persist_112': '탈출 속도',
    'persist_116': '백년 전쟁',
    'persist_120': '필름 시대',
    'persist_122': '가장 긴 인생',
    'persist_125': '판테온',
    'persist_128': '매킨토시 훈장',
    'persist_135': '필름 배지',
    'persist_137': '지구 C-137',
    'persist_144': '마작의 기원',
    'persist_146': '피라미드의 기적',
    'persist_150': '노아의 방주',
    'persist_151': '포켓 몬스터',
    'persist_155': '당구의 전설',
    'persist_165': '얼어붙은 푸른 별',
    'persist_167': '태양계 너머',
    'persist_168': '길상여의',
    'persist_175': '제1 적격자',
    'persist_180': '삼각형 메달',
    'persist_193': '유엔 배지',
    'persist_197': '황금 배지',
    'persist_206': '체르노빌 훈장',
    'persist_214': '강희자전',
    'persist_225': '태백금성',
    'persist_240': '모스크바의 별',
    'persist_243': '금성 식민지',
    'persist_249': '만물생장',
    'persist_250': '은하계 메달',
    'persist_255': '거북이의 축복',
    'persist_260': '마야 시대',
    'persist_277': '모스크바의 바다',
    'persist_280': '새 생명',
    'persist_282': '함무라비 법전',
    'persist_287': '지구 중심 탐험',
    'persist_293': '고대 올림픽',
    'persist_294': '자치통감',
    'persist_305': '시경의 노래',
    'persist_314': '아르키메데스',
    'persist_322': '돌파구',
    'persist_324': '에펠탑',
    'persist_333': '도쿄 타워',
    'persist_360': '메소포타미아 수학',
    'persist_361': '바둑판',
    'persist_365': '사계절',
    'persist_366': '윤년의 약속',
    'persist_382': '단식 챔피언',
    'persist_400': '트랙 메달',
    'persist_403': 'HTTP 403',
    'persist_404': '분실물 센터',
    'persist_410': '엠파이어 스테이트',
    'persist_419': '코스모스 419',
    'persist_437': '우주 비행사',
    'persist_500': '오행산',
    'persist_507': '명나라의 진주',
    'persist_512': '나이팅게일 훈장',
    'persist_520': '사랑 고백',
    'persist_525': '우주 방랑자',
    'persist_527': '콜로세움',
    'persist_601': '순례의 종',
    'persist_666': '핑크 유니콘',
    'persist_687': '화성 기지',
    'persist_828': '두바이의 정상',
    'persist_878': '우주 유영자',
    'persist_930': '첫 번째 사람',
    'persist_1420': '기년전',
    'persist_2997': '광속 메달',
  };

  // ─── 繁體中文名稱 ───

  static const Map<String, String> namesZhHant = {
    'quest_first_session': '第一個爪印',
    'quest_100_sessions': '百次俱樂部',
    'quest_3_habits': '三頭並進',
    'quest_5_habits': '五福臨門',
    'quest_all_done': '全部搞定',
    'quest_5_workdays': '工作日戰士',
    'quest_first_checkin': '簽到喵',
    'quest_marathon': '馬拉松貓',
    'hours_100': '百時征途',
    'hours_1000': '千時大師',
    'goal_on_time': '按時達成',
    'goal_ahead': '提前達標',
    'cat_first_adopt': '歡迎回家',
    'cat_3_adopted': '貓咪收藏家',
    'cat_adolescent': '少年貓',
    'cat_adult': '成年禮',
    'cat_senior': '滿級貓',
    'cat_graduated': '畢業日',
    'cat_accessory': '時尚喵星人',
    'cat_5_accessories': '衣櫃女王',
    'cat_all_happy': '快樂大家庭',
    'persist_1': '一日幸運',
    'persist_2': '不二法門',
    'persist_3': '三生萬物',
    'persist_4': '四大元素',
    'persist_5': '衝出冰山',
    'persist_6': '六芒星',
    'persist_7': '創世之初',
    'persist_8': '搏擊勳章',
    'persist_9': '登月之旅',
    'persist_10': '薄伽丘的祝福',
    'persist_11': '阿波羅 17 號',
    'persist_12': '十二章',
    'persist_13': '冷戰勳章',
    'persist_14': '十四行詩人',
    'persist_15': '滿月勳章',
    'persist_16': '奧運會之旅',
    'persist_17': '獨立宣言',
    'persist_18': '且聽風吟',
    'persist_19': '爾雅之書',
    'persist_20': '命運骰子',
    'persist_21': '聖雄勳章',
    'persist_22': '暴風雪勳章',
    'persist_23': '聖殿騎士勳章',
    'persist_24': '諾曼第勳章',
    'persist_25': '圓桌武士',
    'persist_26': '鋼鐵勳章',
    'persist_27': '進化之手',
    'persist_28': '二十八宿',
    'persist_29': 'Leap Day',
    'persist_30': '月之暗面',
    'persist_31': '獨裁官',
    'persist_32': '黑白之戰',
    'persist_33': '預言之子',
    'persist_35': '三界導師',
    'persist_36': '豬堅強',
    'persist_38': '莎士比亞勳章',
    'persist_41': '莫札特樂章',
    'persist_42': '馬拉松獎章',
    'persist_44': '前往不列顛',
    'persist_45': '半場勳章',
    'persist_47': 'AK-47',
    'persist_48': '秋葉原偶像',
    'persist_50': '孟子的教海',
    'persist_51': '51 區訪客',
    'persist_52': '平行宇宙',
    'persist_53': '季後賽之神',
    'persist_54': 'Joker 小丑牌',
    'persist_59': '飛行者一號',
    'persist_60': '孔子之耳順',
    'persist_64': '任天堂之魂',
    'persist_69': '空中飛人',
    'persist_71': '藍色星球',
    'persist_72': '齊天大聖',
    'persist_73': '富嶽三十六景',
    'persist_76': '彗星之旅',
    'persist_77': '牛郎織女',
    'persist_78': '塔羅幸運',
    'persist_79': '環繞星球',
    'persist_80': '凡爾納的船票',
    'persist_81': '斬妖除魔',
    'persist_84': '殘酷天使',
    'persist_85': '不屈不撓',
    'persist_86': '大象勳章',
    'persist_88': '水星之旅',
    'persist_90': '季度之神',
    'persist_91': '羽蛇神金字塔',
    'persist_92': '核燃料',
    'persist_95': '九五之尊',
    'persist_99': '一步之遙',
    'persist_100': '百折不撓',
    'persist_101': '俯瞰臺北',
    'persist_108': '英雄聚首',
    'persist_112': '飛離地球',
    'persist_116': '百年戰爭',
    'persist_120': '菲林時代',
    'persist_122': '最長人生',
    'persist_125': '萬神廟',
    'persist_128': 'Macintosh 勳章',
    'persist_135': '膠卷徽章',
    'persist_137': '地球 C-137',
    'persist_144': '麻雀起源',
    'persist_146': '金字塔奇蹟',
    'persist_150': '諾亞方舟',
    'persist_151': '寵物精靈',
    'persist_155': '撞球之神',
    'persist_165': '藍色凍星',
    'persist_167': '衝出太陽系',
    'persist_168': '一路發',
    'persist_175': '第一適格者',
    'persist_180': '三角形勳章',
    'persist_193': '聯合國徽章',
    'persist_197': '黃金徽章',
    'persist_206': '車諾比勳章',
    'persist_214': '康熙字典',
    'persist_225': '太白金星',
    'persist_240': '莫斯科之星',
    'persist_243': '金星殖民',
    'persist_249': '萬物生生',
    'persist_250': '銀河系勳章',
    'persist_255': '象龜的祝福',
    'persist_260': '瑪雅時代',
    'persist_277': '莫斯科海',
    'persist_280': '新生命',
    'persist_282': '漢謨拉比法典',
    'persist_287': '地心歷險',
    'persist_293': '古代奧林匹克',
    'persist_294': '資治通鑑',
    'persist_305': '風雅頌',
    'persist_314': '阿基米德',
    'persist_322': '衝破封鎖',
    'persist_324': '巴黎鐵塔',
    'persist_333': '東京鐵塔',
    'persist_360': '美索不達米亞數學家',
    'persist_361': '六合之棋',
    'persist_365': '春夏秋冬',
    'persist_366': '四年之約',
    'persist_382': '斷食之王',
    'persist_400': '田徑獎章',
    'persist_403': 'HTTP 403',
    'persist_404': '失物招領',
    'persist_410': '帝國大廈',
    'persist_419': '宇宙 419',
    'persist_437': '宇宙飛人',
    'persist_500': '五行山',
    'persist_507': '明代珍珠',
    'persist_512': '南丁格爾獎章',
    'persist_520': '表白勳章',
    'persist_525': '漫遊宇宙',
    'persist_527': '羅馬鬥獸場',
    'persist_601': '朝聖鐘塔',
    'persist_666': '粉色獨角獸',
    'persist_687': '火星基地',
    'persist_828': '杜拜尖頂',
    'persist_878': '太空行者',
    'persist_930': '第一個人',
    'persist_1420': '祈年殿',
    'persist_2997': '光速勳章',
  };

  // ─── 日本語説明 ───

  static const Map<String, String> descsJa = {
    'quest_first_session': '初めての集中セッションを完了',
    'quest_100_sessions': '集中セッションを100回完了',
    'quest_3_habits': '同時に3つのクエストをアクティブに',
    'quest_5_habits': '同時に5つのクエストをアクティブに',
    'quest_all_done': '1日で全てのデイリー目標を達成',
    'quest_5_workdays': '任意のクエストで5日以上チェックイン',
    'quest_first_checkin': '初めてのデイリーチェックイン',
    'quest_marathon': '1セッションで120分以上集中',
    'hours_100': '任意のクエストで累計100時間',
    'hours_1000': '任意のクエストで累計1000時間',
    'goal_on_time': '締切前にマイルストーンを達成',
    'goal_ahead': '7日以上早くマイルストーンを達成',
    'cat_first_adopt': '最初の猫を迎える',
    'cat_3_adopted': '猫を3匹迎える',
    'cat_adolescent': '猫が青年期に成長',
    'cat_adult': '猫が成猫期に成長',
    'cat_senior': '猫が累計200時間の集中を達成',
    'cat_graduated': '最初の猫が卒業',
    'cat_accessory': '初めてアクセサリーを装備',
    'cat_5_accessories': 'アクセサリーを5個所有',
    'cat_all_happy': '全てのアクティブな猫が同時に幸せ',
  };

  // ─── 한국어 설명 ───

  static const Map<String, String> descsKo = {
    'quest_first_session': '첫 집중 세션 완료',
    'quest_100_sessions': '집중 세션 100회 완료',
    'quest_3_habits': '동시에 3개 퀘스트 활성화',
    'quest_5_habits': '동시에 5개 퀘스트 활성화',
    'quest_all_done': '하루에 모든 일일 목표 달성',
    'quest_5_workdays': '퀘스트에서 5일 이상 체크인',
    'quest_first_checkin': '첫 일일 체크인 완료',
    'quest_marathon': '1세션에서 120분 이상 집중',
    'hours_100': '퀘스트에서 누적 100시간',
    'hours_1000': '퀘스트에서 누적 1000시간',
    'goal_on_time': '마감 전에 마일스톤 달성',
    'goal_ahead': '7일 이상 일찍 마일스톤 달성',
    'cat_first_adopt': '첫 고양이 입양',
    'cat_3_adopted': '고양이 3마리 입양',
    'cat_adolescent': '고양이가 청소년기에 도달',
    'cat_adult': '고양이가 성묘기에 도달',
    'cat_senior': '고양이가 누적 200시간 집중 달성',
    'cat_graduated': '첫 고양이 졸업',
    'cat_accessory': '처음으로 액세서리 장착',
    'cat_5_accessories': '액세서리 5개 보유',
    'cat_all_happy': '모든 활성 고양이가 동시에 행복',
  };

  // ─── 繁體中文描述 ───

  static const Map<String, String> descsZhHant = {
    'quest_first_session': '完成首次專注',
    'quest_100_sessions': '累計完成 100 次專注',
    'quest_3_habits': '同時擁有 3 個活躍任務',
    'quest_5_habits': '同時擁有 5 個活躍任務',
    'quest_all_done': '一天內完成所有任務的每日目標',
    'quest_5_workdays': '任一任務累計打卡 5 天以上',
    'quest_first_checkin': '首次每日簽到',
    'quest_marathon': '單次專注 120 分鐘以上',
    'hours_100': '任一任務累計 100 小時',
    'hours_1000': '任一任務累計 1000 小時',
    'goal_on_time': '在截止日期前完成里程碑目標',
    'goal_ahead': '提前 7 天以上完成里程碑目標',
    'cat_first_adopt': '領養第一隻貓',
    'cat_3_adopted': '累計領養 3 隻貓',
    'cat_adolescent': '任一貓達到青年期',
    'cat_adult': '任一貓達到成年期',
    'cat_senior': '任一貓累計 200 小時專注',
    'cat_graduated': '首隻貓畢業',
    'cat_accessory': '首次裝備配飾',
    'cat_5_accessories': '擁有 5 件配飾',
    'cat_all_happy': '所有活躍貓同時開心',
  };

  // ─── 日本語称号 ───

  static const Map<String, String> titleNamesJa = {
    'title_marathon_cat': 'マラソンキャット',
    'title_perseverance_star': '忍耐の星',
    'title_centurion': '百時戦士',
    'title_cat_year': '猫年伝説',
    'title_elder_cat': '猫の長老',
    'title_unbreakable': '百折不撓',
    'title_four_seasons': '四季',
    'title_speed_of_light': '光速キャット',
    'title_thousand_hours': '千時伝説',
    'title_ahead_of_time': '時の先駆者',
  };

  // ─── 한국어 칭호 ───

  static const Map<String, String> titleNamesKo = {
    'title_marathon_cat': '마라톤 캣',
    'title_perseverance_star': '인내의 별',
    'title_centurion': '백시간 전사',
    'title_cat_year': '고양이의 해',
    'title_elder_cat': '고양이 장로',
    'title_unbreakable': '백절불굴',
    'title_four_seasons': '사계절',
    'title_speed_of_light': '광속 캣',
    'title_thousand_hours': '천시간 전설',
    'title_ahead_of_time': '시간 선행자',
  };

  // ─── 繁體中文稱號 ───

  static const Map<String, String> titleNamesZhHant = {
    'title_marathon_cat': '馬拉松貓',
    'title_perseverance_star': '毅力新星',
    'title_centurion': '百時戰士',
    'title_cat_year': '貓年傳說',
    'title_elder_cat': '貓咪長老',
    'title_unbreakable': '百折不撓',
    'title_four_seasons': '春夏秋冬',
    'title_speed_of_light': '光速貓',
    'title_thousand_hours': '千時傳奇',
    'title_ahead_of_time': '時光先行者',
  };
}
