/// 成就名称与描述的多语言字符串表。
/// 游戏内容的本地化独立于 ARB 系统管理，便于维护 163 条成就数据。
class AchievementStrings {
  AchievementStrings._();

  /// 根据 locale 获取成就名称。
  static String name(String id, String locale) {
    final map = locale.startsWith('zh') ? _namesZh : _namesEn;
    return map[id] ?? id;
  }

  /// 根据 locale 获取成就描述（仅 quest/streak/cat 类使用，persist 类使用参数化 l10n）。
  static String desc(String id, String locale) {
    final map = locale.startsWith('zh') ? _descsZh : _descsEn;
    return map[id] ?? '';
  }

  // ─── 英文名称 ───

  static const Map<String, String> _namesEn = {
    // Quest (8)
    'quest_first_session': 'First Pawprint',
    'quest_100_sessions': 'Century Club',
    'quest_3_habits': 'Triple Threat',
    'quest_5_habits': 'Full House',
    'quest_all_done': 'Clean Sweep',
    'quest_5_workdays': 'Weekday Warrior',
    'quest_first_checkin': 'Morning Cat',
    'quest_marathon': 'Marathon Cat',

    // Streak (8)
    'streak_3': 'Warming Up',
    'streak_7': 'One Week Wonder',
    'streak_14': 'Fortnight Fighter',
    'streak_21': 'Three Week Hero',
    'streak_30': 'Monthly Master',
    'streak_49': 'Seven Weeks Strong',
    'streak_100': 'Centurion',
    'streak_365': 'Year of the Cat',

    // Cat (9)
    'cat_first_adopt': 'Welcome Home',
    'cat_3_adopted': 'Cat Collector',
    'cat_adolescent': 'Growing Up',
    'cat_adult': 'All Grown Up',
    'cat_senior': 'Master Cat',
    'cat_graduated': 'Graduation Day',
    'cat_accessory': 'Fashion Cat',
    'cat_5_accessories': 'Wardrobe Queen',
    'cat_all_happy': 'Happy Family',

    // Persist (138)
    'persist_1': 'Lucky Day',
    'persist_2': 'The Only Way',
    'persist_3': 'Three Breeds All',
    'persist_4': 'Four Elements',
    'persist_5': 'Breaking the Ice',
    'persist_6': 'Hexagram',
    'persist_7': 'Genesis',
    'persist_8': 'Fighter Medal',
    'persist_9': 'Lunar Landing',
    'persist_10': "Boccaccio's Blessing",
    'persist_11': 'Apollo 17',
    'persist_12': 'Twelve Chapters',
    'persist_13': 'Cold War Medal',
    'persist_14': 'The Sonneteer',
    'persist_15': 'Full Moon Medal',
    'persist_16': 'Olympic Journey',
    'persist_17': 'Declaration',
    'persist_18': 'Hear the Wind Sing',
    'persist_19': 'Book of Elegance',
    'persist_20': 'Dice of Destiny',
    'persist_21': 'Mahatma Medal',
    'persist_22': 'Blizzard Medal',
    'persist_23': 'Templar Medal',
    'persist_24': 'Normandy Medal',
    'persist_25': 'Knights of the Round',
    'persist_26': 'Iron Medal',
    'persist_27': 'Hand of Evolution',
    'persist_28': 'Twenty-Eight Mansions',
    'persist_29': 'Leap Day',
    'persist_30': 'Dark Side of the Moon',
    'persist_31': 'The Dictator',
    'persist_32': 'Black & White',
    'persist_33': 'Child of Prophecy',
    'persist_35': 'Master of Three Realms',
    'persist_36': 'Zhu Jianqiang',
    'persist_38': 'Shakespeare Medal',
    'persist_41': "Mozart's Movement",
    'persist_42': 'Marathon Medal',
    'persist_44': 'To Britannia',
    'persist_45': 'Halftime Medal',
    'persist_47': 'AK-47',
    'persist_48': 'Akihabara Idol',
    'persist_50': "Mencius' Teachings",
    'persist_51': 'Area 51 Visitor',
    'persist_52': 'Parallel Universe',
    'persist_53': 'Playoff Legend',
    'persist_54': 'Joker Card',
    'persist_59': 'Flyer No. 1',
    'persist_60': 'Confucius at Sixty',
    'persist_64': 'Nintendo Spirit',
    'persist_69': 'Frequent Flyer',
    'persist_71': 'Blue Planet',
    'persist_72': 'Monkey King',
    'persist_73': 'Thirty-Six Views',
    'persist_76': 'Comet Journey',
    'persist_77': 'Star-Crossed',
    'persist_78': 'Tarot Fortune',
    'persist_79': 'Orbiting Planet',
    'persist_80': "Verne's Ticket",
    'persist_81': 'Demon Slayer',
    'persist_84': 'Cruel Angel',
    'persist_85': 'Indomitable',
    'persist_86': 'Elephant Medal',
    'persist_88': 'Mercury Journey',
    'persist_90': 'Quarterly Legend',
    'persist_91': 'Quetzalcoatl Pyramid',
    'persist_92': 'Nuclear Fuel',
    'persist_95': 'Imperial Supreme',
    'persist_99': 'One Step Away',
    'persist_100': 'Unbreakable',
    'persist_101': 'Taipei Overlook',
    'persist_108': 'Heroes Unite',
    'persist_112': 'Escape Velocity',
    'persist_116': "Hundred Years' War",
    'persist_120': 'Film Era',
    'persist_122': 'Longest Life',
    'persist_125': 'Pantheon',
    'persist_128': 'Macintosh Medal',
    'persist_135': 'Film Roll Badge',
    'persist_137': 'Earth C-137',
    'persist_144': 'Mahjong Origins',
    'persist_146': 'Pyramid Wonder',
    'persist_150': "Noah's Ark",
    'persist_151': 'Pocket Monsters',
    'persist_155': 'Billiards Legend',
    'persist_165': 'Frozen Blue Star',
    'persist_167': 'Beyond the Solar System',
    'persist_168': 'Lucky Prosperity',
    'persist_175': 'First Candidate',
    'persist_180': 'Triangle Medal',
    'persist_193': 'UN Badge',
    'persist_197': 'Golden Badge',
    'persist_206': 'Chernobyl Medal',
    'persist_214': 'Kangxi Dictionary',
    'persist_225': 'Venus Star',
    'persist_240': 'Star of Moscow',
    'persist_243': 'Venus Colony',
    'persist_249': 'All Things Flourish',
    'persist_250': 'Galaxy Medal',
    'persist_255': "Tortoise's Blessing",
    'persist_260': 'Mayan Era',
    'persist_277': 'Moscow Sea',
    'persist_280': 'New Life',
    'persist_282': 'Code of Hammurabi',
    'persist_287': 'Journey to the Center',
    'persist_293': 'Ancient Olympics',
    'persist_294': 'Comprehensive Mirror',
    'persist_305': 'Songs of Elegance',
    'persist_314': 'Archimedes',
    'persist_322': 'Breaking Through',
    'persist_324': 'Eiffel Tower',
    'persist_333': 'Tokyo Tower',
    'persist_360': 'Mesopotamian Math',
    'persist_361': 'Go Board',
    'persist_365': 'Four Seasons',
    'persist_366': 'Leap Year Promise',
    'persist_382': 'Fasting Champion',
    'persist_400': 'Track Medal',
    'persist_403': 'HTTP 403',
    'persist_404': 'Lost & Found',
    'persist_410': 'Empire State',
    'persist_419': 'Cosmos 419',
    'persist_437': 'Cosmic Flyer',
    'persist_500': 'Five-Element Mountain',
    'persist_507': 'Ming Pearl',
    'persist_512': 'Nightingale Medal',
    'persist_520': 'Love Declaration',
    'persist_525': 'Cosmic Wanderer',
    'persist_527': 'Colosseum',
    'persist_601': "Pilgrim's Bell",
    'persist_666': 'Pink Unicorn',
    'persist_687': 'Mars Base',
    'persist_828': 'Dubai Pinnacle',
    'persist_878': 'Spacewalker',
    'persist_930': 'The First One',
    'persist_1420': 'Temple of Heaven',
    'persist_2997': 'Speed of Light',
  };

  // ─── 中文名称 ───

  static const Map<String, String> _namesZh = {
    // Quest (8)
    'quest_first_session': '第一个爪印',
    'quest_100_sessions': '百次俱乐部',
    'quest_3_habits': '三头并进',
    'quest_5_habits': '五福临门',
    'quest_all_done': '全部搞定',
    'quest_5_workdays': '工作日战士',
    'quest_first_checkin': '签到喵',
    'quest_marathon': '马拉松猫',

    // Streak (8)
    'streak_3': '热身三天',
    'streak_7': '一周达成',
    'streak_14': '两周坚持',
    'streak_21': '三周英雄',
    'streak_30': '月度大师',
    'streak_49': '七七四十九',
    'streak_100': '百日征程',
    'streak_365': '猫年传说',

    // Cat (9)
    'cat_first_adopt': '欢迎回家',
    'cat_3_adopted': '猫咪收藏家',
    'cat_adolescent': '少年猫',
    'cat_adult': '成年礼',
    'cat_senior': '满级猫',
    'cat_graduated': '毕业日',
    'cat_accessory': '时尚喵星人',
    'cat_5_accessories': '衣柜女王',
    'cat_all_happy': '快乐大家庭',

    // Persist (138)
    'persist_1': '一日幸运',
    'persist_2': '不二法门',
    'persist_3': '三生万物',
    'persist_4': '四大元素',
    'persist_5': '冲出冰山',
    'persist_6': '六芒星',
    'persist_7': '创世之初',
    'persist_8': '搏击勋章',
    'persist_9': '登月之旅',
    'persist_10': '薄伽丘的祝福',
    'persist_11': '阿波罗 17 号',
    'persist_12': '十二章',
    'persist_13': '冷战勋章',
    'persist_14': '十四行诗人',
    'persist_15': '满月勋章',
    'persist_16': '奥运会之旅',
    'persist_17': '独立宣言',
    'persist_18': '且听风吟',
    'persist_19': '尔雅之书',
    'persist_20': '命运骰子',
    'persist_21': '圣雄勋章',
    'persist_22': '暴风雪勋章',
    'persist_23': '圣殿骑士勋章',
    'persist_24': '诺曼底勋章',
    'persist_25': '圆桌武士',
    'persist_26': '钢铁勋章',
    'persist_27': '进化之手',
    'persist_28': '二十八宿',
    'persist_29': 'Leap Day',
    'persist_30': '月之暗面',
    'persist_31': '独裁官',
    'persist_32': '黑白之战',
    'persist_33': '预言之子',
    'persist_35': '三界导师',
    'persist_36': '猪坚强',
    'persist_38': '莎士比亚勋章',
    'persist_41': '莫扎特乐章',
    'persist_42': '马拉松奖章',
    'persist_44': '前往不列颠',
    'persist_45': '半场勋章',
    'persist_47': 'AK-47',
    'persist_48': '秋叶原偶像',
    'persist_50': '孟子的教海',
    'persist_51': '51 区访客',
    'persist_52': '平行宇宙',
    'persist_53': '季后赛之神',
    'persist_54': 'Joker 小丑牌',
    'persist_59': '飞行者一号',
    'persist_60': '孔子之耳顺',
    'persist_64': '任天堂之魂',
    'persist_69': '空中飞人',
    'persist_71': '蓝色星球',
    'persist_72': '齐天大圣',
    'persist_73': '富岳三十六景',
    'persist_76': '彗星之旅',
    'persist_77': '牛郎织女',
    'persist_78': '塔罗幸运',
    'persist_79': '环绕星球',
    'persist_80': '凡尔纳的船票',
    'persist_81': '斩妖除魔',
    'persist_84': '残酷天使',
    'persist_85': '不屈不挠',
    'persist_86': '大象勋章',
    'persist_88': '水星之旅',
    'persist_90': '季度之神',
    'persist_91': '羽蛇神金字塔',
    'persist_92': '核燃料',
    'persist_95': '九五之尊',
    'persist_99': '一步之遥',
    'persist_100': '百折不挠',
    'persist_101': '俯瞰台北',
    'persist_108': '英雄聚首',
    'persist_112': '飞离地球',
    'persist_116': '百年战争',
    'persist_120': '菲林时代',
    'persist_122': '最长人生',
    'persist_125': '万神庙',
    'persist_128': 'Macintosh 勋章',
    'persist_135': '胶卷徽章',
    'persist_137': '地球 C-137',
    'persist_144': '麻雀起源',
    'persist_146': '金字塔奇迹',
    'persist_150': '诺亚方舟',
    'persist_151': '宠物精灵',
    'persist_155': '桌球之神',
    'persist_165': '蓝色冻星',
    'persist_167': '冲出太阳系',
    'persist_168': '一路發',
    'persist_175': '第一适格者',
    'persist_180': '三角形勋章',
    'persist_193': '联合国徽章',
    'persist_197': '黄金徽章',
    'persist_206': '切尔诺贝利勋章',
    'persist_214': '康熙字典',
    'persist_225': '太白金星',
    'persist_240': '莫斯科之星',
    'persist_243': '金星殖民',
    'persist_249': '万物生生',
    'persist_250': '银河系勋章',
    'persist_255': '象龟的祝福',
    'persist_260': '玛雅时代',
    'persist_277': '莫斯科海',
    'persist_280': '新生命',
    'persist_282': '汉谟拉比法典',
    'persist_287': '地心历险',
    'persist_293': '古代奥林匹克',
    'persist_294': '资治通鉴',
    'persist_305': '风雅颂',
    'persist_314': '阿基米德',
    'persist_322': '冲破封锁',
    'persist_324': '巴黎铁塔',
    'persist_333': '东京铁塔',
    'persist_360': '美索不达米亚数学家',
    'persist_361': '六合之棋',
    'persist_365': '春夏秋冬',
    'persist_366': '四年之约',
    'persist_382': '断食之王',
    'persist_400': '田径奖章',
    'persist_403': 'HTTP 403',
    'persist_404': '失物招领',
    'persist_410': '帝国大厦',
    'persist_419': '宇宙 419',
    'persist_437': '宇宙飞人',
    'persist_500': '五行山',
    'persist_507': '明代珍珠',
    'persist_512': '南丁格尔奖章',
    'persist_520': '表白勋章',
    'persist_525': '漫游宇宙',
    'persist_527': '罗马斗兽场',
    'persist_601': '朝圣钟塔',
    'persist_666': '粉色独角兽',
    'persist_687': '火星基地',
    'persist_828': '迪拜尖顶',
    'persist_878': '太空行者',
    'persist_930': '第一个人',
    'persist_1420': '祈年殿',
    'persist_2997': '光速勋章',
  };

  // ─── 英文描述（quest/streak/cat，persist 使用参数化 l10n）───

  static const Map<String, String> _descsEn = {
    // Quest
    'quest_first_session': 'Complete your first focus session',
    'quest_100_sessions': 'Complete 100 focus sessions',
    'quest_3_habits': 'Have 3 active quests at the same time',
    'quest_5_habits': 'Have 5 active quests at the same time',
    'quest_all_done': 'Complete all daily goals in one day',
    'quest_5_workdays': 'Check in 5 consecutive weekdays',
    'quest_first_checkin': 'Complete your first daily check-in',
    'quest_marathon': 'Focus for 120+ minutes in one session',

    // Streak
    'streak_3': '3-day streak on any quest',
    'streak_7': '7-day streak on any quest',
    'streak_14': '14-day streak on any quest',
    'streak_21': '21-day streak on any quest',
    'streak_30': '30-day streak on any quest',
    'streak_49': '49-day streak on any quest',
    'streak_100': '100-day streak on any quest',
    'streak_365': '365-day streak on any quest',

    // Cat
    'cat_first_adopt': 'Adopt your first cat',
    'cat_3_adopted': 'Adopt 3 cats in total',
    'cat_adolescent': 'A cat reaches the adolescent stage',
    'cat_adult': 'A cat reaches the adult stage',
    'cat_senior': 'A cat completes 100% of its growth target',
    'cat_graduated': 'Graduate your first cat',
    'cat_accessory': 'Equip an accessory for the first time',
    'cat_5_accessories': 'Own 5 accessories',
    'cat_all_happy': 'All active cats are happy at the same time',
  };

  // ─── 中文描述 ───

  static const Map<String, String> _descsZh = {
    // Quest
    'quest_first_session': '完成首次专注',
    'quest_100_sessions': '累计完成 100 次专注',
    'quest_3_habits': '同时拥有 3 个活跃任务',
    'quest_5_habits': '同时拥有 5 个活跃任务',
    'quest_all_done': '一天内完成所有任务的每日目标',
    'quest_5_workdays': '连续 5 个工作日打卡',
    'quest_first_checkin': '首次每日签到',
    'quest_marathon': '单次专注 120 分钟以上',

    // Streak
    'streak_3': '任一任务连续 3 天',
    'streak_7': '任一任务连续 7 天',
    'streak_14': '任一任务连续 14 天',
    'streak_21': '任一任务连续 21 天',
    'streak_30': '任一任务连续 30 天',
    'streak_49': '任一任务连续 49 天',
    'streak_100': '任一任务连续 100 天',
    'streak_365': '任一任务连续 365 天',

    // Cat
    'cat_first_adopt': '领养第一只猫',
    'cat_3_adopted': '累计领养 3 只猫',
    'cat_adolescent': '任一猫达到少年期',
    'cat_adult': '任一猫达到成年期',
    'cat_senior': '任一猫完成 100% 成长目标',
    'cat_graduated': '首只猫毕业',
    'cat_accessory': '首次装备配饰',
    'cat_5_accessories': '拥有 5 件配饰',
    'cat_all_happy': '所有活跃猫同时开心',
  };

  // ─── 称号名称 ───

  static const Map<String, String> _titleNamesEn = {
    'title_marathon_cat': 'Marathon Cat',
    'title_perseverance_star': 'Perseverance Star',
    'title_centurion': 'Centurion',
    'title_cat_year': 'Year of the Cat',
    'title_elder_cat': 'Cat Elder',
    'title_unbreakable': 'Unbreakable',
    'title_four_seasons': 'Four Seasons',
    'title_speed_of_light': 'Speed of Light',
  };

  static const Map<String, String> _titleNamesZh = {
    'title_marathon_cat': '马拉松猫',
    'title_perseverance_star': '毅力新星',
    'title_centurion': '百日战士',
    'title_cat_year': '猫年传说',
    'title_elder_cat': '猫咪长老',
    'title_unbreakable': '百折不挠',
    'title_four_seasons': '春夏秋冬',
    'title_speed_of_light': '光速猫',
  };

  /// 获取称号显示名称。
  static String titleName(String titleId, String locale) {
    final map = locale.startsWith('zh') ? _titleNamesZh : _titleNamesEn;
    return map[titleId] ?? titleId;
  }
}
