import 'dart:math';
import 'dart:ui';

/// 激励语库 — 每种语言 20+ 条，覆盖全部 15 种语言。
/// 遵循 achievement_strings.dart 的静态 Map 模式，游戏内容 i18n 独立于 ARB。
const Map<String, List<String>> _quotes = {
  'en': [
    'Small steps lead to big changes.',
    'Every minute counts.',
    'Progress, not perfection.',
    'You are stronger than you think.',
    'One day at a time.',
    'The secret of getting ahead is getting started.',
    'Discipline is choosing what you want most.',
    'Focus on the journey, not the destination.',
    'Believe you can and you are halfway there.',
    'A little progress each day adds up.',
    'Your future self will thank you.',
    'Start where you are, use what you have.',
    'Consistency beats intensity.',
    'The best time to start is now.',
    'Great things take time.',
    'Keep going, you are doing great.',
    'Build habits, build a life.',
    'Success is the sum of small efforts.',
    'Make today count.',
    'Stay focused, stay determined.',
    'Do it for the cat!',
    'Be patient with yourself.',
    'Dream big, start small, act now.',
  ],
  'zh': [
    '日月逝矣，时不我待。',
    '千里之行，始于足下。',
    '积少成多，聚沙成塔。',
    '坚持就是胜利。',
    '今日事，今日毕。',
    '不积跬步，无以至千里。',
    '每一分钟都有意义。',
    '做更好的自己。',
    '星星之火，可以燎原。',
    '天道酬勤。',
    '进步比完美更重要。',
    '滴水穿石，非一日之功。',
    '自律即自由。',
    '你比想象中更强大。',
    '好习惯成就好人生。',
    '今天也要加油呀！',
    '慢慢来，比较快。',
    '专注当下，不负时光。',
    '成功是每个小努力的总和。',
    '相信过程，静待花开。',
    '为了猫猫，冲！',
    '一步一个脚印。',
    '耐心是最好的捷径。',
  ],
  'zh-Hant': [
    '日月逝矣，時不我待。',
    '千里之行，始於足下。',
    '積少成多，聚沙成塔。',
    '堅持就是勝利。',
    '今日事，今日畢。',
    '不積跬步，無以至千里。',
    '每一分鐘都有意義。',
    '做更好的自己。',
    '星星之火，可以燎原。',
    '天道酬勤。',
    '進步比完美更重要。',
    '滴水穿石，非一日之功。',
    '自律即自由。',
    '你比想像中更強大。',
    '好習慣成就好人生。',
    '今天也要加油呀！',
    '慢慢來，比較快。',
    '專注當下，不負時光。',
    '成功是每個小努力的總和。',
    '相信過程，靜待花開。',
    '為了貓貓，衝！',
    '一步一個腳印。',
    '耐心是最好的捷徑。',
  ],
  'ja': [
    '千里の道も一歩から。',
    '継続は力なり。',
    '今日も一歩前へ。',
    '小さな積み重ねが大きな成果に。',
    '自分を信じて。',
    '一日一日を大切に。',
    '努力は裏切らない。',
    '焦らず、一歩ずつ。',
    '今できることに集中しよう。',
    '昨日より今日の自分。',
    '完璧より前進を。',
    '習慣が人生を変える。',
    '自分のペースでいい。',
    '未来の自分が感謝する。',
    '今日が最高の始まり。',
    '夢は大きく、始まりは小さく。',
    '集中力が未来を作る。',
    '毎分が大切な時間。',
    '諦めなければ、負けない。',
    'にゃんこのために頑張ろう！',
    '一歩一歩、確実に。',
    '変化は小さな行動から。',
    '今この瞬間を楽しもう。',
  ],
  'ko': [
    '천리 길도 한 걸음부터.',
    '꾸준함이 최고의 능력이다.',
    '오늘도 한 걸음 더.',
    '작은 노력이 큰 변화를 만든다.',
    '나를 믿자.',
    '하루하루가 소중하다.',
    '노력은 배신하지 않는다.',
    '조급해하지 말고 한 걸음씩.',
    '지금 할 수 있는 것에 집중하자.',
    '어제보다 나은 오늘.',
    '완벽보다 성장이 중요하다.',
    '습관이 인생을 바꾼다.',
    '나만의 속도로 괜찮아.',
    '미래의 내가 고마워할 거야.',
    '오늘이 최고의 시작이다.',
    '크게 꿈꾸고 작게 시작하자.',
    '집중이 미래를 만든다.',
    '매 순간이 소중한 시간.',
    '포기하지 않으면 진 게 아니다.',
    '고양이를 위해 파이팅!',
    '한 걸음 한 걸음 확실하게.',
    '변화는 작은 행동에서 시작된다.',
    '지금 이 순간을 즐기자.',
  ],
  'de': [
    'Kleine Schritte führen zu großen Veränderungen.',
    'Jede Minute zählt.',
    'Fortschritt, nicht Perfektion.',
    'Du bist stärker, als du denkst.',
    'Ein Tag nach dem anderen.',
    'Das Geheimnis des Vorankommens ist der Anfang.',
    'Disziplin bedeutet zu wählen, was dir am wichtigsten ist.',
    'Konzentriere dich auf den Weg, nicht auf das Ziel.',
    'Glaube an dich und du bist schon halb da.',
    'Ein kleiner Fortschritt jeden Tag summiert sich.',
    'Dein zukünftiges Ich wird dir danken.',
    'Beginne dort, wo du bist.',
    'Beständigkeit schlägt Intensität.',
    'Die beste Zeit anzufangen ist jetzt.',
    'Große Dinge brauchen Zeit.',
    'Mach weiter so, du machst das großartig.',
    'Baue Gewohnheiten, baue ein Leben.',
    'Erfolg ist die Summe kleiner Anstrengungen.',
    'Mach den heutigen Tag besonders.',
    'Bleib fokussiert, bleib entschlossen.',
    'Tu es für die Katze!',
    'Sei geduldig mit dir selbst.',
  ],
  'es': [
    'Pequeños pasos llevan a grandes cambios.',
    'Cada minuto cuenta.',
    'Progreso, no perfección.',
    'Eres más fuerte de lo que piensas.',
    'Un día a la vez.',
    'El secreto de avanzar es empezar.',
    'La disciplina es elegir lo que más quieres.',
    'Enfócate en el camino, no en el destino.',
    'Cree que puedes y ya estás a medio camino.',
    'Un pequeño progreso cada día se acumula.',
    'Tu yo futuro te lo agradecerá.',
    'Empieza donde estás, usa lo que tienes.',
    'La constancia supera la intensidad.',
    'El mejor momento para empezar es ahora.',
    'Las grandes cosas toman tiempo.',
    'Sigue así, lo estás haciendo genial.',
    'Construye hábitos, construye una vida.',
    'El éxito es la suma de pequeños esfuerzos.',
    'Haz que hoy cuente.',
    'Mantente enfocado y determinado.',
    '¡Hazlo por el gato!',
    'Ten paciencia contigo mismo.',
  ],
  'fr': [
    'Les petits pas mènent aux grands changements.',
    'Chaque minute compte.',
    'Le progrès, pas la perfection.',
    'Tu es plus fort que tu ne le penses.',
    'Un jour à la fois.',
    'Le secret pour avancer, c\'est de commencer.',
    'La discipline, c\'est choisir ce qui compte le plus.',
    'Concentre-toi sur le voyage, pas la destination.',
    'Crois en toi et tu es déjà à mi-chemin.',
    'Un petit progrès chaque jour s\'accumule.',
    'Ton futur toi te remerciera.',
    'Commence là où tu es, utilise ce que tu as.',
    'La constance bat l\'intensité.',
    'Le meilleur moment pour commencer, c\'est maintenant.',
    'Les grandes choses prennent du temps.',
    'Continue, tu fais du super travail.',
    'Construis des habitudes, construis une vie.',
    'Le succès est la somme de petits efforts.',
    'Fais en sorte qu\'aujourd\'hui compte.',
    'Reste concentré, reste déterminé.',
    'Fais-le pour le chat !',
    'Sois patient avec toi-même.',
  ],
  'it': [
    'Piccoli passi portano a grandi cambiamenti.',
    'Ogni minuto conta.',
    'Progresso, non perfezione.',
    'Sei più forte di quanto pensi.',
    'Un giorno alla volta.',
    'Il segreto per avanzare è iniziare.',
    'La disciplina è scegliere ciò che vuoi di più.',
    'Concentrati sul viaggio, non sulla destinazione.',
    'Credi di poterlo fare e sei già a metà strada.',
    'Un piccolo progresso ogni giorno si accumula.',
    'Il tuo futuro te stesso ti ringrazierà.',
    'Inizia da dove sei, usa quello che hai.',
    'La costanza batte l\'intensità.',
    'Il momento migliore per iniziare è adesso.',
    'Le grandi cose richiedono tempo.',
    'Continua così, stai andando alla grande.',
    'Costruisci abitudini, costruisci una vita.',
    'Il successo è la somma di piccoli sforzi.',
    'Fai contare la giornata di oggi.',
    'Resta concentrato e determinato.',
    'Fallo per il gatto!',
    'Sii paziente con te stesso.',
  ],
  'pt': [
    'Pequenos passos levam a grandes mudanças.',
    'Cada minuto conta.',
    'Progresso, não perfeição.',
    'Você é mais forte do que imagina.',
    'Um dia de cada vez.',
    'O segredo de progredir é começar.',
    'Disciplina é escolher o que você mais quer.',
    'Foque na jornada, não no destino.',
    'Acredite que pode e já está na metade do caminho.',
    'Um pequeno progresso a cada dia se acumula.',
    'Seu eu futuro vai agradecer.',
    'Comece de onde está, use o que tem.',
    'Consistência supera intensidade.',
    'O melhor momento para começar é agora.',
    'Grandes coisas levam tempo.',
    'Continue assim, você está indo muito bem.',
    'Construa hábitos, construa uma vida.',
    'O sucesso é a soma de pequenos esforços.',
    'Faça hoje valer a pena.',
    'Mantenha o foco e a determinação.',
    'Faça pelo gato!',
    'Tenha paciência consigo mesmo.',
  ],
  'hi': [
    'छोटे कदम बड़े बदलाव लाते हैं।',
    'हर मिनट मायने रखता है।',
    'प्रगति, पूर्णता नहीं।',
    'तुम अपनी सोच से ज़्यादा मज़बूत हो।',
    'एक बार में एक दिन।',
    'आगे बढ़ने का राज़ शुरू करना है।',
    'अनुशासन वो चुनना है जो सबसे ज़रूरी है।',
    'सफ़र पर ध्यान दो, मंज़िल पर नहीं।',
    'विश्वास करो कि तुम कर सकते हो।',
    'हर दिन थोड़ी प्रगति जुड़ती जाती है।',
    'भविष्य का तुम शुक्रिया कहेगा।',
    'जहाँ हो वहीं से शुरू करो।',
    'निरंतरता तीव्रता को हराती है।',
    'शुरू करने का सबसे अच्छा समय अभी है।',
    'बड़ी चीज़ों में वक़्त लगता है।',
    'चलते रहो, तुम बहुत अच्छा कर रहे हो।',
    'आदतें बनाओ, जीवन बनाओ।',
    'सफलता छोटे प्रयासों का योग है।',
    'आज को ख़ास बनाओ।',
    'केंद्रित रहो, दृढ़ रहो।',
    'बिल्ली के लिए करो!',
    'अपने साथ धैर्य रखो।',
  ],
  'th': [
    'ก้าวเล็กๆ นำไปสู่การเปลี่ยนแปลงใหญ่',
    'ทุกนาทีมีค่า',
    'ก้าวหน้า ไม่ใช่สมบูรณ์แบบ',
    'คุณแข็งแกร่งกว่าที่คิด',
    'วันละหนึ่งวัน',
    'เคล็ดลับของการก้าวหน้าคือการเริ่มต้น',
    'วินัยคือการเลือกสิ่งที่คุณต้องการมากที่สุด',
    'มุ่งเน้นที่การเดินทาง ไม่ใช่จุดหมาย',
    'เชื่อว่าทำได้ คุณก็ไปถึงครึ่งทางแล้ว',
    'ความก้าวหน้าเล็กๆ ทุกวันสะสมขึ้นเรื่อยๆ',
    'ตัวคุณในอนาคตจะขอบคุณ',
    'เริ่มจากจุดที่คุณอยู่ ใช้สิ่งที่มี',
    'ความสม่ำเสมอชนะความเข้มข้น',
    'เวลาที่ดีที่สุดในการเริ่มต้นคือตอนนี้',
    'สิ่งยิ่งใหญ่ต้องใช้เวลา',
    'สู้ต่อไป คุณทำได้ดีมาก',
    'สร้างนิสัย สร้างชีวิต',
    'ความสำเร็จคือผลรวมของความพยายามเล็กๆ',
    'ทำให้วันนี้มีค่า',
    'มีสมาธิ มุ่งมั่น',
    'ทำเพื่อน้องแมว!',
    'อดทนกับตัวเอง',
  ],
  'vi': [
    'Những bước nhỏ dẫn đến thay đổi lớn.',
    'Mỗi phút đều có giá trị.',
    'Tiến bộ, không phải hoàn hảo.',
    'Bạn mạnh hơn bạn nghĩ.',
    'Từng ngày một.',
    'Bí quyết để tiến lên là bắt đầu.',
    'Kỷ luật là chọn điều bạn muốn nhất.',
    'Tập trung vào hành trình, không phải đích đến.',
    'Tin rằng bạn có thể và bạn đã đi được nửa đường.',
    'Tiến bộ nhỏ mỗi ngày sẽ tích lũy.',
    'Bạn trong tương lai sẽ cảm ơn bạn.',
    'Bắt đầu từ nơi bạn đang đứng.',
    'Kiên trì thắng cường độ.',
    'Thời điểm tốt nhất để bắt đầu là bây giờ.',
    'Những điều lớn lao cần thời gian.',
    'Tiếp tục đi, bạn đang làm rất tốt.',
    'Xây dựng thói quen, xây dựng cuộc sống.',
    'Thành công là tổng của những nỗ lực nhỏ.',
    'Hãy làm cho ngày hôm nay có ý nghĩa.',
    'Giữ tập trung, giữ quyết tâm.',
    'Làm vì mèo nào!',
    'Hãy kiên nhẫn với chính mình.',
  ],
  'id': [
    'Langkah kecil membawa perubahan besar.',
    'Setiap menit berarti.',
    'Kemajuan, bukan kesempurnaan.',
    'Kamu lebih kuat dari yang kamu kira.',
    'Satu hari pada satu waktu.',
    'Rahasia untuk maju adalah memulai.',
    'Disiplin adalah memilih apa yang paling kamu inginkan.',
    'Fokus pada perjalanan, bukan tujuan.',
    'Percayalah kamu bisa dan kamu sudah setengah jalan.',
    'Kemajuan kecil setiap hari akan bertambah.',
    'Dirimu di masa depan akan berterima kasih.',
    'Mulai dari mana kamu berada, gunakan apa yang kamu punya.',
    'Konsistensi mengalahkan intensitas.',
    'Waktu terbaik untuk memulai adalah sekarang.',
    'Hal-hal besar butuh waktu.',
    'Terus berjalan, kamu sudah hebat.',
    'Bangun kebiasaan, bangun kehidupan.',
    'Sukses adalah jumlah usaha-usaha kecil.',
    'Jadikan hari ini berarti.',
    'Tetap fokus, tetap tekun.',
    'Lakukan untuk si kucing!',
    'Bersabarlah dengan dirimu sendiri.',
  ],
  'tr': [
    'Küçük adımlar büyük değişimlere yol açar.',
    'Her dakika önemli.',
    'İlerleme, mükemmellik değil.',
    'Düşündüğünden daha güçlüsün.',
    'Bir günde bir gün.',
    'İlerlemenin sırrı başlamaktır.',
    'Disiplin, en çok istediğini seçmektir.',
    'Yolculuğa odaklan, varış noktasına değil.',
    'Yapabileceğine inan ve yarı yoldasın.',
    'Her gün küçük bir ilerleme birikir.',
    'Gelecekteki sen sana teşekkür edecek.',
    'Olduğun yerden başla, sahip olduğunu kullan.',
    'Tutarlılık yoğunluğu yener.',
    'Başlamanın en iyi zamanı şimdi.',
    'Büyük şeyler zaman alır.',
    'Devam et, harika gidiyorsun.',
    'Alışkanlıklar kur, hayat kur.',
    'Başarı küçük çabaların toplamıdır.',
    'Bugünü değerli kıl.',
    'Odaklı kal, kararlı kal.',
    'Kedi için yap!',
    'Kendine karşı sabırlı ol.',
  ],
};

/// 根据 locale 获取激励语列表，fallback 到英文。
List<String> _quotesForLocale(Locale locale) {
  // 优先匹配 languageCode-scriptCode（如 zh-Hant）
  if (locale.scriptCode != null) {
    final key = '${locale.languageCode}-${locale.scriptCode}';
    if (_quotes.containsKey(key)) return _quotes[key]!;
  }
  return _quotes[locale.languageCode] ?? _quotes['en']!;
}

final _random = Random();

/// 随机获取一条激励语，避免连续重复。
String randomMotivationQuote(Locale locale, {String? exclude}) {
  final pool = _quotesForLocale(locale);
  final filtered = exclude != null
      ? pool.where((q) => q != exclude).toList()
      : pool;
  return filtered[_random.nextInt(filtered.length)];
}
